#############################################################
# Makefile for SPIWriter program for the OMAP-L138          #
#############################################################
#	    
PROGRAM:=SPIWriter


# Target definitions
.PHONY : all clean
all: 
#		timake $(PROGRAM)_ARM.pjt Debug
		timake $(PROGRAM)_DSP.pjt Debug

clean:
#		timake $(PROGRAM)_ARM.pjt Debug -clean
		timake $(PROGRAM)_DSP.pjt Debug -clean



